
# Common configuration parameters:
database:
  # Database URL. (required)
  url: "postgres://postgres@leader_db:5432/postgres"
logging_config:
  force_json_output: true

# Aggregation job driver-related parameters:
min_job_discovery_delay_secs: 1
max_job_discovery_delay_secs: 10
worker_lease_duration_secs: 600
worker_lease_clock_skew_allowance_secs: 60
max_concurrent_job_workers: 10
job_discovery_interval_secs: 10
# Number of times to attempt processing an aggregation job before abandoning it.
# (required)
maximum_attempts_before_failure: 10

# Number of sharded database records per batch aggregation. Must not be greater
# than the equivalent setting in the collection job driver. (required)
batch_aggregation_shard_count: 32