FROM rust:1.79.0-alpine as builder
ENV CARGO_INCREMENTAL=0
ARG SQLX_VERSION="0.7.2"
RUN apk add libc-dev
RUN cargo install sqlx-cli \
    --version ${SQLX_VERSION} \
    --no-default-features --features rustls,postgres


FROM postgres:15-alpine
ARG SQLX_VERSION="0.7.2"
LABEL sqlx_version ${SQLX_VERSION}
COPY --from=builder /usr/local/cargo/bin/sqlx /sqlx
COPY db /migrations
# ENTRYPOINT ["/sqlx"]