# Common configuration parameters:
# https://github.com/divviup/janus/blob/main/docs/samples/basic_config/collection_job_driver.yaml
database:
  url: "postgres://postgres@leader_db:5432/postgres"
logging_config:
  force_json_output: true

# Maximum interval on which to acquire incomplete collection jobs. (required)
job_discovery_interval_s: 10

# Duration of leases of collection jobs being processed. (required)
worker_lease_duration_secs: 600
# Maximum allowable clock skew used when identifying expired leases on
# collection jobs. (required)
worker_lease_clock_skew_allowance_secs: 60
max_concurrent_job_workers: 10
# Number of times to attempt processing an collection job before abandoning it.
# (required)
maximum_attempts_before_failure: 10

# Number of sharded database records per batch aggregation. Must not be less
# than the equivalent setting in the aggregator and aggregation job driver.
# (required)
batch_aggregation_shard_count: 32