# based on: https://github.com/divviup/janus/blob/main/docs/samples/basic_config/aggregator.yaml

# Common configuration parameters:

database:
  # Database URL. (required)
  url: "postgres://postgres@leader_db:5432/postgres"

# Socket address for /healthz and /traceconfigz HTTP requests. Defaults to 127.0.0.1:9001.
health_check_listen_address: "0.0.0.0:9001"

# Aggregator-specific parameters:

# Socket address for DAP requests. (required)
listen_address: "0.0.0.0:80"

# Maximum interval on which to acquire incomplete collection jobs. (required)
job_discovery_interval_secs: 10

# Maximum number of uploaded reports per batching transaction. (required)
max_upload_batch_size: 100

# Maximum delay before writing a batch of uploaded reports. (required)
max_upload_batch_write_delay_ms: 250

# Number of sharded database records per batch aggregation. Must not be greater
# than the equivalent setting in the collection job driver. (required)
batch_aggregation_shard_count: 32

logging_config:
  force_json_output: true
